---
extends: default
rules:
  line-length:
    max: 160
ignore:
  - tests
  - changelogs/changelog.yaml
#  - playbooks
level: warning

rules:
  indentation: 
    level: warning
  line-length:
    level: warning
  trailing-spaces:
    level: warning
  new-line-at-end-of-file:
    level: warning
  key-duplicates:
    level: warning