---
namespace: cisco
name: dnac
version: 1.0.0
readme: README.md
authors:
- Rafael Campos <rcampos@altus.cr>
- William Astorga <wastorga@altus.cr>
- Jose Bogarin <jbogarin@altus.cr>
description: Ansible Modules for Cisco DNA Center
license_file: 'LICENSE'
tags:
- cisco
- dnac
- cloud
- collection
- networking
- sdn
repository: https://github.com/cisco-en-programmability/dnacenter-ansible
documentation: https://docs.ansible.com/ansible/latest/scenario_guides/guide_dnac.html
homepage: https://github.com/cisco-en-programmability/dnacenter-ansible
issues: https://github.com/cisco-en-programmability/dnacenter-ansible.git/issues
