- hosts: dnac_servers
  vars_files:
    - credentials_dnac.yml
    - device_details.yml
  gather_facts: no
  connection: local
  tasks:
#
# Project Info  Section
#
    - name: Test project template      
      cisco.dnac.template_module:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: True
        state: "merged"
        #ignore_errors: true        #Enable this to continue execution even the task fails
        config:
        - project_name: "{{ item.proj_name }}"
          template_content: "{{ item.device_config }}"
          language: "{{ item.language }}"
          device_types:
          - productFamily: "{{ item.family }}"
          software_type: "{{ item.type }}"
          software_variant: "{{ item.variant }}"
          template_name: "{{ item.temp_name }}"
          version_description: "{{ item.description }}"
      register: template_result
      with_items: '{{ template_details }}'
      tags:
        - template


    - name: Create pnp
      cisco.dnac.pnp_module:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        config:
        - type: "{{ item.site_type }}"
          site:
            building:
              latitude: "{{ item.bld_lat }}"
              longitude: "{{ item.bld_long }}"
              name: "{{ item.bld_name }}"
              parentName: "{{ item.site_name }}"
          project_name: "{{ item.proj_name }}"
          template_name: "{{ item.temp_name }}"
          #golden_image: True
          image_name: "{{ item.image_name }}"
          device_version: "{{ item.device_version }}"
          deviceInfo:
            serialNumber: "{{ item.device_number }}"
            hostname: "{{ item.device_name}}"
            state: "{{ item.device_state }}"
            pid: "{{ item.device_id }}"
      register: pnp_result
      with_items: '{{ device_details }}'
      tags:
        - pnp
