- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get all tasks
    cisco.dnac.application_set:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      # state: query
      # count: True
      #
      # state: delete
      # id: 45798514-9e74-4c5c-bbce-3689028d7b10
      #
      state: create
      payload:
        - name: AppSet1
        - name: AppSet2
    register: result

  - name: Show retrieved tasks
    debug:
      msg: "{{ result }}"

  - name: Get task tree
    cisco.dnac.task:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query
      task_id: "{{ result.dnac_response.response.taskId }}"
      tree: True
    register: result

  - name: Show retrieved task
    debug:
      msg: "{{ result.dnac_response.response }}"

