- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create/delete/update/query object
    cisco.dnac.event_subscription:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      
      # state: create
      # payload:
      # - subscriptionId: "<string>"
      #   version: "<string>"
      #   name: "<string>"
      #   description: "<string>"
      #   subscriptionEndpoints:
      #   - instanceId: "<string>"
      #     subscriptionDetails:
      #       name: "<string>"
      #       url: "<string>"
      #       method: "<string>"
      #       connectorType: "<string>"
      #   - instanceId: "<string>"
      #     subscriptionDetails:
      #       name: "<string>"
      #       url: "<string>"
      #       method: "<string>"
      #       connectorType: "<string>"
      #   filter:
      #     eventIds:
      #     - "<string>"
      #     - "<string>"
      #
      state: query
    register: result

  - name: Show task id
    debug:
      msg: "{{ result }}"


  - name: Get task tree
    cisco.dnac.task:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query
      task_id: "{{ result.dnac_response.response.taskId }}"
      tree: True
    register: result

  - name: Show retrieved task
    debug:
      msg: "{{ result.dnac_response.response }}"
