- hosts: dnac_servers
  gather_facts: no
  tasks:
  - name: Create/delete/update/query object
    cisco.dnac.flow_analysis:
      # state: query
      # flow_analysis_id: 84305942-0f78-4db8-b379-32d298d3077a
      #
      state: create
      destIP: 1.1.1.18
      sourceIP: 1.1.1.17  
      #
      # state: delete
      # flow_analysis_id: 84305942-0f78-4db8-b379-32d298d3077a

    register: result

  - name: Show task id
    debug:
      msg: "{{ result }}"
