- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get network device
    cisco.dnac.network_device:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      
      state: query
      #count: True
      #id: 84305942-0f78-4db8-b379-32d298d3077a
      summary: True
      #ip_address: 1.1.1.14
      #serial_number: FLM2213W05R
      #records_to_return: 2
      #start_index: 3
      #
      # state: delete
      # id: 84305942-0f78-4db8-b379-32d298d3077a
    register: result

  - name: Show task id
    debug:
      msg: "{{ result }}"
