- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete global credential cli
    cisco.dnac.global_credential_cli:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: create
      payload:
      - enablePassword: C1$c0123
        username: ansible_tests
        password: Al7u$123
      # 
      # state: update
      # enablePassword: C1$c0123
      # username: ansible_tests
      # password: Al7u$123
      # 
    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     