- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete import image file
    cisco.dnac.import_image_file:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: create
      filename: test.template  # string
      filepath: files/test.template  # string
      is_third_party: True  # boolean
      third_party_application_type: SomeValue  # string
      third_party_image_family: SomeValue  # string
      third_party_vendor: SomeValue  # string
       
    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     