- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete network device register
    cisco.dnac.network_device_register:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query
      macaddress: AA:BB:CC:DD:EE:FF
      serial_number: abc123
      #
      # state: create
      # payload:
      #
      # state: delete
      # id:
      # 
      # state: update
      # id:
      # 
    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"