- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get data
    cisco.dnac.network_device_polling_interval:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query
      #id: 41d610bf-f131-47d2-84d6-9dc72c757c6f
    register: result

  - name: Show data
    debug:
      msg: "{{ result }}"
