- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete network device poller legit reads
    cisco.dnac.network_device_poller_legit_reads:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query

    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     