- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete nfv profile
    cisco.dnac.nfv_profile:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query
      id: SomeValue  # string
      #
      # state: create
      # profileName: SomeValue  # string
      # device:
      # - deviceType: SomeValue # string
      #   deviceTag: SomeValue # string
      #   serviceProviderProfile:
      #     serviceProvider: False  # boolean
      #     linkType: SomeValue # string
      #     connect: False  # boolean
      #     connectDefaultGatewayOnWan: False  # boolean
      #   directInternetAccessForFirewall: False  # boolean
      #   services:
      #     serviceType: SomeValue # string
      #     profileType: SomeValue # string
      #     serviceName: SomeValue # string
      #     imageName: SomeValue # string
      #     vNicMapping:
      #       networkType: SomeValue # string
      #       assignIpAddressToNetwork: SomeValue # string
      #     firewallMode: SomeValue # string
      #   customNetworks:
      #     networkName: SomeValue # string
      #     servicesToConnect:
      #       serviceName: SomeValue # string
      #     connectionType: SomeValue # string
      #     vlanMode: SomeValue # string
      #     vlanId: SomeValue # string
      #   vlanForL2:
      #   customTemplate:
      #
      # state: delete
      # id: SomeValue  # string
      # 
      # state: update
      # id: SomeValue  # string
      # profileName: SomeValue  # string
      # device:
      # - deviceType: SomeValue # string
      #   deviceTag: SomeValue # string
      #   serviceProviderProfile:
      #     serviceProvider: False  # boolean
      #     linkType: SomeValue # string
      #     connect: False  # boolean
      #     connectDefaultGatewayOnWan: False  # boolean
      #   directInternetAccessForFirewall: False  # boolean
      #   services:
      #     serviceType: SomeValue # string
      #     profileType: SomeValue # string
      #     serviceName: SomeValue # string
      #     imageName: SomeValue # string
      #     vNicMapping:
      #       networkType: SomeValue # string
      #       assignIpAddressToNetwork: SomeValue # string
      #     firewallMode: SomeValue # string
      #   customNetworks:
      #     networkName: SomeValue # string
      #     servicesToConnect:
      #       serviceName: SomeValue # string
      #     connectionType: SomeValue # string
      #     vlanMode: SomeValue # string
      #     vlanId: SomeValue # string
      #   vlanForL2:
      #   customTemplate:
      # 
    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     