- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete pnp device import
    cisco.dnac.pnp_device_import:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: create
      payload:
      - _id: SomeValue  # string
        deviceInfo:
          source: SomeValue  # string
          serialNumber: SomeValue  # string
          stack: False  # boolean
          mode: SomeValue  # string
          state: SomeValue  # string
          location:
            siteId: SomeValue  # string
            address: SomeValue  # string
            latitude: SomeValue  # string
            longitude: SomeValue  # string
            altitude: SomeValue  # string
          description: SomeValue  # string
          onbState: SomeValue  # string
          authenticatedMicNumber: SomeValue  # string
          authenticatedSudiSerialNo: SomeValue  # string
          capabilitiesSupported:
          - SomeValue  # string
          - SomeValue  # string
          featuresSupported:
          - SomeValue  # string
          - SomeValue  # string
          cmState: SomeValue  # string
          firstContact: 1  # number
          lastContact: 1  # number
          macAddress: SomeValue  # string
          pid: SomeValue  # string
          deviceSudiSerialNos:
          - SomeValue  # string
          - SomeValue  # string
          lastUpdateOn: 1  # number
          workflowId: SomeValue  # string
          workflowName: SomeValue  # string
          projectId: SomeValue  # string
          projectName: SomeValue  # string
          deviceType: SomeValue  # string
          agentType: SomeValue  # string
          imageVersion: SomeValue  # string
          fileSystemList:
          - type: SomeValue  # string
            writeable: False  # boolean
            freespace: 1  # number
            name: SomeValue  # string
            readable: False  # boolean
            size: 1  # number
          - type: SomeValue  # string
            writeable: False  # boolean
            freespace: 1  # number
            name: SomeValue  # string
            readable: False  # boolean
            size: 1  # number
          pnpProfileList:
          - profileName: SomeValue  # string
            discoveryCreated: False  # boolean
            createdBy: SomeValue  # string
            primaryEndpoint:
              port: 1  # number
              protocol: SomeValue  # string
              ipv4Address:   # object/dictionary
              ipv6Address:   # object/dictionary
              fqdn: SomeValue  # string
              certificate: SomeValue  # string
            secondaryEndpoint:
              port: 1  # number
              protocol: SomeValue  # string
              ipv4Address:   # object/dictionary
              ipv6Address:   # object/dictionary
              fqdn: SomeValue  # string
              certificate: SomeValue  # string
          - profileName: SomeValue  # string
            discoveryCreated: False  # boolean
            createdBy: SomeValue  # string
            primaryEndpoint:
              port: 1  # number
              protocol: SomeValue  # string
              ipv4Address:   # object/dictionary
              ipv6Address:   # object/dictionary
              fqdn: SomeValue  # string
              certificate: SomeValue  # string
            secondaryEndpoint:
              port: 1  # number
              protocol: SomeValue  # string
              ipv4Address:   # object/dictionary
              ipv6Address:   # object/dictionary
              fqdn: SomeValue  # string
              certificate: SomeValue  # string
          imageFile: SomeValue  # string
          httpHeaders:
          - key: SomeValue  # string
            value: SomeValue  # string
          - key: SomeValue  # string
            value: SomeValue  # string
          neighborLinks:
          - localInterfaceName: SomeValue  # string
            localShortInterfaceName: SomeValue  # string
            localMacAddress: SomeValue  # string
            remoteInterfaceName: SomeValue  # string
            remoteShortInterfaceName: SomeValue  # string
            remoteMacAddress: SomeValue  # string
            remoteDeviceName: SomeValue  # string
            remotePlatform: SomeValue  # string
            remoteVersion: SomeValue  # string
          - localInterfaceName: SomeValue  # string
            localShortInterfaceName: SomeValue  # string
            localMacAddress: SomeValue  # string
            remoteInterfaceName: SomeValue  # string
            remoteShortInterfaceName: SomeValue  # string
            remoteMacAddress: SomeValue  # string
            remoteDeviceName: SomeValue  # string
            remotePlatform: SomeValue  # string
            remoteVersion: SomeValue  # string
          lastSyncTime: 1  # number
          ipInterfaces:
          - status: SomeValue  # string
            macAddress: SomeValue  # string
            ipv4Address:   # object/dictionary
            name: SomeValue  # string
          - status: SomeValue  # string
            macAddress: SomeValue  # string
            ipv4Address:   # object/dictionary
            name: SomeValue  # string
          hostname: SomeValue  # string
          authStatus: SomeValue  # string
          stackInfo:
            supportsStackWorkflows: False  # boolean
            isFullRing: False  # boolean
            stackMemberList:
            - serialNumber: SomeValue  # string
              state: SomeValue  # string
              role: SomeValue  # string
              macAddress: SomeValue  # string
              pid: SomeValue  # string
              licenseLevel: SomeValue  # string
              licenseType: SomeValue  # string
              sudiSerialNumber: SomeValue  # string
              hardwareVersion: SomeValue  # string
              stackNumber: 1  # number
              softwareVersion: SomeValue  # string
              priority: 1  # number
            - serialNumber: SomeValue  # string
              state: SomeValue  # string
              role: SomeValue  # string
              macAddress: SomeValue  # string
              pid: SomeValue  # string
              licenseLevel: SomeValue  # string
              licenseType: SomeValue  # string
              sudiSerialNumber: SomeValue  # string
              hardwareVersion: SomeValue  # string
              stackNumber: 1  # number
              softwareVersion: SomeValue  # string
              priority: 1  # number
            stackRingProtocol: SomeValue  # string
            validLicenseLevels:
            - SomeValue  # string
            - SomeValue  # string
            totalMemberCount: 1  # number
          reloadRequested: False  # boolean
          addedOn: 1  # number
          siteId: SomeValue  # string
          aaaCredentials:
            password: SomeValue  # string
            username: SomeValue  # string
          userMicNumbers:
          - SomeValue  # string
          - SomeValue  # string
          userSudiSerialNos:
          - SomeValue  # string
          - SomeValue  # string
          addnMacAddrs:
          - SomeValue  # string
          - SomeValue  # string
          preWorkflowCliOuputs:
          - cli: SomeValue  # string
            cliOutput: SomeValue  # string
          - cli: SomeValue  # string
            cliOutput: SomeValue  # string
          tags:   # object/dictionary
          sudiRequired: False  # boolean
          smartAccountId: SomeValue  # string
          virtualAccountId: SomeValue  # string
          populateInventory: False  # boolean
          siteName: SomeValue  # string
          name: SomeValue  # string
        systemResetWorkflow:
          _id: SomeValue  # string
          state: SomeValue  # string
          type: SomeValue  # string
          description: SomeValue  # string
          lastupdateOn: 1  # number
          imageId: SomeValue  # string
          currTaskIdx: 1  # number
          addedOn: 1  # number
          tasks:
          - state: SomeValue  # string
            type: SomeValue  # string
            currWorkItemIdx: 1  # number
            taskSeqNo: 1  # number
            endTime: 1  # number
            startTime: 1  # number
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            name: SomeValue  # string
          - state: SomeValue  # string
            type: SomeValue  # string
            currWorkItemIdx: 1  # number
            taskSeqNo: 1  # number
            endTime: 1  # number
            startTime: 1  # number
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            name: SomeValue  # string
          addToInventory: False  # boolean
          instanceType: SomeValue  # string
          endTime: 1  # number
          execTime: 1  # number
          startTime: 1  # number
          useState: SomeValue  # string
          configId: SomeValue  # string
          name: SomeValue  # string
          version: 1  # number
          tenantId: SomeValue  # string
        systemWorkflow:
          _id: SomeValue  # string
          state: SomeValue  # string
          type: SomeValue  # string
          description: SomeValue  # string
          lastupdateOn: 1  # number
          imageId: SomeValue  # string
          currTaskIdx: 1  # number
          addedOn: 1  # number
          tasks:
          - state: SomeValue  # string
            type: SomeValue  # string
            currWorkItemIdx: 1  # number
            taskSeqNo: 1  # number
            endTime: 1  # number
            startTime: 1  # number
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            name: SomeValue  # string
          - state: SomeValue  # string
            type: SomeValue  # string
            currWorkItemIdx: 1  # number
            taskSeqNo: 1  # number
            endTime: 1  # number
            startTime: 1  # number
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            name: SomeValue  # string
          addToInventory: False  # boolean
          instanceType: SomeValue  # string
          endTime: 1  # number
          execTime: 1  # number
          startTime: 1  # number
          useState: SomeValue  # string
          configId: SomeValue  # string
          name: SomeValue  # string
          version: 1  # number
          tenantId: SomeValue  # string
        workflow:
          _id: SomeValue  # string
          state: SomeValue  # string
          type: SomeValue  # string
          description: SomeValue  # string
          lastupdateOn: 1  # number
          imageId: SomeValue  # string
          currTaskIdx: 1  # number
          addedOn: 1  # number
          tasks:
          - state: SomeValue  # string
            type: SomeValue  # string
            currWorkItemIdx: 1  # number
            taskSeqNo: 1  # number
            endTime: 1  # number
            startTime: 1  # number
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            name: SomeValue  # string
          - state: SomeValue  # string
            type: SomeValue  # string
            currWorkItemIdx: 1  # number
            taskSeqNo: 1  # number
            endTime: 1  # number
            startTime: 1  # number
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            name: SomeValue  # string
          addToInventory: False  # boolean
          instanceType: SomeValue  # string
          endTime: 1  # number
          execTime: 1  # number
          startTime: 1  # number
          useState: SomeValue  # string
          configId: SomeValue  # string
          name: SomeValue  # string
          version: 1  # number
          tenantId: SomeValue  # string
        runSummaryList:
        - details: SomeValue  # string
          historyTaskInfo:
            type: SomeValue  # string
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            addnDetails:
            - key: SomeValue  # string
              value: SomeValue  # string
            - key: SomeValue  # string
              value: SomeValue  # string
            name: SomeValue  # string
          errorFlag: False  # boolean
          timestamp: 1  # number
        - details: SomeValue  # string
          historyTaskInfo:
            type: SomeValue  # string
            workItemList:
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            - state: SomeValue  # string
              command: SomeValue  # string
              outputStr: SomeValue  # string
              endTime: 1  # number
              startTime: 1  # number
              timeTaken: 1  # number
            timeTaken: 1  # number
            addnDetails:
            - key: SomeValue  # string
              value: SomeValue  # string
            - key: SomeValue  # string
              value: SomeValue  # string
            name: SomeValue  # string
          errorFlag: False  # boolean
          timestamp: 1  # number
        workflowParameters:
          topOfStackSerialNumber: SomeValue  # string
          licenseLevel: SomeValue  # string
          licenseType: SomeValue  # string
          configList:
          - configParameters:
            - key: SomeValue  # string
              value: SomeValue  # string
            - key: SomeValue  # string
              value: SomeValue  # string
            configId: SomeValue  # string
          - configParameters:
            - key: SomeValue  # string
              value: SomeValue  # string
            - key: SomeValue  # string
              value: SomeValue  # string
            configId: SomeValue  # string
        version: 1  # number
        tenantId: SomeValue  # string


     
    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     