- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create pnp device reset
    cisco.dnac.pnp_device_reset:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: create
      deviceResetList:
      - configList:
        - configId: SomeValue  # string
          configParameters:
          - key: SomeValue  # string
            value: SomeValue  # string
          - key: SomeValue  # string
            value: SomeValue  # string
        - configId: SomeValue  # string
          configParameters:
          - key: SomeValue  # string
            value: SomeValue  # string
          - key: SomeValue  # string
            value: SomeValue  # string
        deviceId: SomeValue  # string
        licenseLevel: SomeValue  # string
        licenseType: SomeValue  # string
        topOfStackSerialNumber: SomeValue  # string
      - configList:
        - configId: SomeValue  # string
          configParameters:
          - key: SomeValue  # string
            value: SomeValue  # string
          - key: SomeValue  # string
            value: SomeValue  # string
        - configId: SomeValue  # string
          configParameters:
          - key: SomeValue  # string
            value: SomeValue  # string
          - key: SomeValue  # string
            value: SomeValue  # string
        deviceId: SomeValue  # string
        licenseLevel: SomeValue  # string
        licenseType: SomeValue  # string
        topOfStackSerialNumber: SomeValue  # string
      projectId: SomeValue  # string
      workflowId: SomeValue  # string

    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     