- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete control plane device
    cisco.dnac.sda_control_plane_device:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      # state: query
      # device_ipaddress: 1.1.1.17
      #
      state: create
      payload:
      - deviceManagementIpAddress: 1.1.1.17
        siteNameHierarchy: Global/Brasil

    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"
