- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete border device
    cisco.dnac.sda_border_device:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      # state: query
      # device_ipaddress: 1.1.1.17
      #
      state: create
      payload: 
      - deviceManagementIpAddress: 2.2.2.2
        siteNameHierarchy: Global/Brasil
        externalDomainRoutingProtocolName: BGP
        externalConnectivityIpPoolName: MyPool
        internalAutonomouSystemNumber: '51'
        borderSessionType: EXTERNAL
        connectedToInternet: true
        externalConnectivitySettings:
        - interfaceName: MyInterface
          externalAutonomouSystemNumber: '25'
          l3Handoff:
          - virtualNetwork:
              virtualNetworkName: MyVNetworkName



    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"
