- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete edge device
    cisco.dnac.ssid:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      # state: delete
      # managed_aplocations: MyApps
      # ssid_name: MySSID
      # 
      state: create
      managedAPLocations:
      - Location 1
      - Location 2
      ssidDetails:
        name: SSIDName
        securityLevel: WPA2_ENTERPRISE
        enableFastLane: False
        passphrase: mysecretpassphrase
        trafficType: data
        enableBroadcastSSID: True
        radioPolicy: Dual band operation (2.4GHz and 5GHz)
        enableMACFiltering: False
        fastTransition: Adaptive
        webAuthURL: https://mywebauthurl.com
      ssidType: Enterprise
      enableFabric: True
      flexConnect:
        enableFlexConnect: True
        localToVlan: 1

    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"
