- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get/create/delete tag member
    cisco.dnac.tag_member:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      # state: query
      # id: a0951ec8-7dcb-4709-92e7-fd3825dd36fb
      # member_type: networkinterface
      # count: true
      #
      # state: create
      # id: a0951ec8-7dcb-4709-92e7-fd3825dd36fb
      #
      # state: delete
      # id: a0951ec8-7dcb-4709-92e7-fd3825dd36fb
      # member_type: networkinterface
      # 
      state: update
      memberToTags:
        key:
        - SomeOtherKey
        - SomeKey
      memberType: networkinterface
    register: result

  - name: Show retrieved object
    debug:
      msg: "{{ result }}"     