- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get all tasks
    cisco.dnac.task:
      dnac_host: 192.168.196.2
      dnac_port: 443
      dnac_username: altus
      dnac_password: Altus123
      dnac_version: 2.1.1
      dnac_verify: False
      #
      state: query
      #count: True
    register: result

  - name: Show retrieved tasks
    debug:
      msg: "{{ result }}"
