---
- name: Discover devices
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "{{ CLUSTERFILE }}"

  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: True
      dnac_log_level: DEBUG

  tasks:
    - name: Execute discovery devices using MULTI RANGE
      cisco.dnac.discovery_intent:
        <<: *dnac_login
        state: merged
        config_verify: True
        config:
          - ip_address_list:
              - 204.1.2.1 #It will be taken as 204.1.2.1 - 204.1.2.1
              - 205.2.1.1-205.2.1.10
            discovery_type: "MULTI RANGE"
            discovery_name: File_111
            protocol_order: ssh
            start_index: 1
            records_to_return: 25
            snmp_version: v2

    - name: Execute discovery devices using CDP/LLDP/CIDR
      cisco.dnac.discovery_intent:
        <<: *dnac_login
        state: merged
        config_verify: True
        config:
          - ip_address_list:   #List length should be one
              - 204.1.2.1
            discovery_type: "CDP" #Can be LLDP and CIDR
            cdp_level: 16 #Instead use lldp for LLDP and prefix length for CIDR
            discovery_name: CDP_Test_1
            protocol_order: ssh
            start_index: 1
            records_to_return: 25
            snmp_version: v2