---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "input_inventory.yml"
    - "credentials.yml"
  tasks:
    - name: Add/Update/Resync/Delete the devices in Cisco DNA Center Inventory.
      cisco.dnac.inventory_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log_level: DEBUG
        dnac_log: true
        config_verify: true
        state: merged
        config:
          # - ip_address_list:
          #     - 204.1.2.1
          #   clean_config: False
          - provision_wired_device:
            - device_ip: "204.1.2.1"
              site_name: "Global/Chennai/LTTS/FLOOR1"