- hosts: dnac_servers
  vars_files:
    - credentials_245.yml
  gather_facts: no
  connection: local
  tasks:
#
# Project Info  Section
#

    - name: Create, update, delete global pool and reserve an ip pool
      cisco.dnac.sample_module:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: True
        state: merged
        config:
        - GlobalPoolDetails:
            settings:
              ippool:
              - ipPoolName: Global_Pool1
                gateway: "" #use this for updating
                IpAddressSpace: IPv4 #required when we are creating
                ipPoolCidr: 100.0.0.0/8  #required when we are creating
                type: Generic
                dhcpServerIps: [] #use this for updating
                dnsServerIps: [] #use this for updating
                # prev_name: Global_Pool
          ReservePoolDetails:
            ipv6AddressSpace: false
            ipv4GlobalPool: 100.0.0.0/8 
            ipv4Prefix: true
            ipv4PrefixLength: 8
            ipv4DnsServers: []
            name: IP_Pool_3
            siteName: Global/Chennai/Trill
            slaacSupport: true
            # prev_name: IP_Pool_4
            type: LAN
          NetworkManagementDetails:
            settings:
              dhcpServer:
              - 10.0.0.1
              dnsServer:
                domainName: cisco.co
                primaryIpAddress: 10.0.0.2
                secondaryIpAddress: 10.0.0.3
              # clientAndEndpoint_aaa:                    #works only if we system settigns is set
              #   # ipAddress: string #Mandatory for ISE, sec ip for AAA
              #   network: 10.0.0.9
              #   protocol: RADIUS                                          
              #   servers: AAA
              #   # sharedSecret: string #ISE
              messageOfTheday:
                bannerMessage: hello
                retainExistingBanner: "true"
              netflowcollector:
                ipAddress: 10.0.0.4
                port: 443
              # network_aaa:                              #works only if we system settigns is set
              #   # ipAddress: string #Mandatory for ISE, sec ip for AAA
              #   network: 10.0.0.8
              #   protocol: RADIUS
              #   servers: AAA
              #   # sharedSecret: string #ISE
              ntpServer:
              - 10.0.0.5
              snmpServer:
                configureDnacIP: true
                ipAddresses:
                - 10.0.0.6
              syslogServer:
                configureDnacIP: true
                ipAddresses:
                - 10.0.0.7
              timezone: GMT
            siteName: Global/Chennai

