---
- name: Testing
  hosts: dnac_servers
  gather_facts: no

  vars_files:
    - "credentials.yml"

  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: true
      dnac_log_level: DEBUG
      config_verify: true

  tasks:

    - name: Testing
      cisco.dnac.network_compliance_workflow_manager:
        <<: *dnac_login
        config:
        - ip_address_list: ['204.1.2.2', '204.1.2.5', '204.1.2.4']
          site_name: "Global"
          run_compliance:
            trigger_full: True
            categories: ['INTENT','RUNNING_CONFIG']
          sync_device_config: False
