---
# Playbook 1 Create the Network wireless profile workflow manager
- name: Create network wireless profile on Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Create network profile for wireless
      cisco.dnac.network_profile_wireless_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        offset_limit: 500
        state: merged
        config:
          - profile_name: "Campus_Wireless_Profile_1"
            site_names:
              - "Global/Madurai"
              - "Global/China"
              - "Global/tamilnadu"
            ssid_details:
              # - ssid: "GuestLTTS"
              #   enable_fabric: false
              #   wlan_profile_name: "GuestLTTS_profile"
              #   policy_profile_name: "GuestLTTS_profile"
              #   vlan_group_name: "test_vlan_group_1"
              - ssid: "NY_SSID"
                enable_fabric: false
                wlan_profile_name: "NY_SSID_Profile"
                policy_profile_name: "NY_SSID_Profile"
                interface_name: "test_interface_1"
                local_to_vlan: 2001
            ap_zones:
              - ap_zone_name: "AP_Zone_North"
                rf_profile_name: "LOW"
                ssids:
                  # - "GuestLTTS"
                  - "NY_SSID"
            additional_interfaces:
              - interface_name: "test_interface_1"
                vlan_id: 20
              - interface_name: "test_interface_2"
                vlan_id: 22
            # onboarding_templates:
            #   - "Ansible_PNP_Switch"
            #   - "Example_test1"
            day_n_templates:
              - "WLC Template"
              # - "Template Provisioning To Device"
              # - "test_template"

          # - profile_name: "Enterprise_Wireless_Profile_1"
          #   site_names:
          #     - "Global/Chennai"
          #     - "Global/Madurai"
          #   ssid_details:
          #     - ssid: "HQ_WiFi"
          #       enable_fabric: false
          #       wlan_profile_name: "HQ_WiFi_Profile"
          #       policy_profile_name: "HQ_Access"
          #       vlan_group_name: "VLAN_Group_20"
          #     - ssid: "Branch_Secure"
          #       enable_fabric: false
          #       wlan_profile_name: "Branch_Secure_Profile"
          #       policy_profile_name: "Branch_Access"
          #       interface_name: "GigabitEthernet0/4"
          #       local_to_vlan: 35
          #   ap_zones:
          #     - ap_zone_name: "AP_Zone_South"
          #       rf_profile_name: "Medium_Performance"
          #       ssids:
          #         - "HQ_WiFi"
          #         - "Branch_Secure"
          #   additional_interfaces:
          #     - interface_name: "GigabitEthernet0/5"
          #       vlan_id: 30
          #     - interface_name: "GigabitEthernet0/6"
          #       vlan_id: 35
          #   onboarding_templates:
          #     - "Test_template"
          #   day_n_templates:
          #     - "WLC Template"
      register: output_list
