--- 
# Playbook 1 Create the Network switch profile workflow manager
- name: Create network switch profile on Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Create network profile for switch
      cisco.dnac.network_switch_profile_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        offset_limit: 500
        state: merged
        config:
          - profile_name: "test_switch_1"
            onboarding_templates:
              - "Ansible_PNP_Switch"
              - "test_template"
            day_n_templates:
              - "Template Provisioning To Device"
            site_names:
              - "Global/APO"
              - "Global/Abc"
          - profile_name: "test_switch_2"
            onboarding_templates:
              - "Ansible_PNP_Switch"
            day_n_templates:
              - "Template Provisioning To Device"
            site_names:
              - "Global/Chennai"
              - "Global/Madurai"
      register: output_list
