---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Add/Update/Resync/Delete the devices in Cisco DNA Center Inventory.
      cisco.dnac.provision_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log_level: DEBUG
        dnac_log: true
        config_verify: true
        state: merged
        config:
          - site_name_hierarchy: Global/USA/San Jose/BLDG23
            management_ip_address: 204.1.2.2
          - site_name_hierarchy: Global/Chennai/LTTS/FLOOR1
            management_ip_address: 204.1.2.4
          - site_name_hierarchy: Global/USA/SAN JOSE/BLD23
            management_ip_address: 204.192.3.40 
            managed_ap_locations:
              - Global/Chennai/LTTS/FLOOR1