---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Provision a wired device to a site
      cisco.dnac.provision_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - application_telemetry:
              - device_ips: [
                    "204.1.2.5",
                    "204.1.1.101",
                    "204.1.2.4",
                    "204.1.2.2",
                    "204.1.2.6",
                    "204.1.2.7",
                    "204.1.2.8",
                    "204.1.2.9",
                    "204.1.2.3",
                    "204.1.2.70",
                    "204.1.2.1",
                    "204.1.2.69"
                    ]
                telemetry: enable
