- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Provision a wired device to a site
      cisco.dnac.provision_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - site_name_hierarchy: Global/Chennai/LTTS/FLOOR1
            management_ip_address: 204.192.6.200
            interfaces:
              - interface_name: Vlan1866
                vlan_id: 1866
                interface_ip_address: 204.192.6.200
                interface_gateway: 204.192.6.1
            skip_ap_provision: false
            rolling_ap_upgrade:
              enable_rolling_ap_upgrade: false
              ap_reboot_percentage: 5