---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "input_swim.yml"
    - "credentials.yml"
  tasks:
    - name: Import an image, tag it as golden and load it on device
      cisco.dnac.swim_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        config:
          # - import_image_details:
          #     type: CCO
          #     cco_image_details:
          #         image_name: [cat9k_iosxe.17.12.02.SPA.bin, cat9k_iosxe_npe.17.09.05.SPA.bin]

            - import_image_details:
                type: remote
                url_details:
                    payload:
                    - source_url: [http://sdaso.cisco.com/swim/alpha/cat9k_iosxe.17.17.01prd5.SPA.bin]
                      is_third_party: False
          # - image_activation_details:
          #     image_name: cat9k_iosxe.17.12.02.SPA.bin
          #     site_name: Global/Chennai/LTTS/FLOOR11
          #     device_role: ALL
          #     device_family_name: Switches and Hubs
          #     device_series_name: Cisco Catalyst 9300 Series Switches
          #     scehdule_validate: False
          #     activate_lower_image_version: True
          #     distribute_if_needed: True

          # - image_distribution_details:
          #     image_name: cat9k_iosxe.17.12.02.SPA.bin
          #     site_name: Global/Chennai/LTTS/FLOOR11
          #     device_role: ALL
          #     device_family_name: Switches and Hubs
          #     device_series_name: Cisco Catalyst 9300 Series Switches