---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "input_swim.yml"
    - "credentials.yml"
  tasks:
    - name: Import an image, tag it as golden and load it on device
      cisco.dnac.swim_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        config:
          - tagging_details:
              image_name: cat9k_iosxe.17.15.01.SPA.bin
              device_role: core, distribution
              device_image_family_name: Cisco Catalyst 9300 Switch
              # site_name: Global/Chennai/LTTS/FLOOR1
              tagging: False


          # - image_distribution_details:
          #     site_name: Global/Chennai/LTTS/FLOOR1
          #     device_image_family_name: Cisco Catalyst 9300 Switch
          #     device_role: CORE
          #     device_family_name: Switches and Hubs
          #     device_series_name: Cisco Catalyst 9300 Series Switches

          # - image_distribution_details:
          #     # image_name: cat9k_iosxe.17.12.01.SPA.bin
          #     site_name: Global/USA/San Francisco/BGL_18
          #     device_role: ALL
          #     device_family_name: Switches and Hubs
          #     device_series_name: Cisco Catalyst 9300 Series Switches