---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "input_swim.yml"
    - "credentials.yml"
  tasks:
    - name: Import an image, tag it as golden and load it on device
      cisco.dnac.swim_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        config:
        - import_image_details:
            type: remote
            url_details:
                payload:
                  - source_url:  http://sdaso.cisco.com/swim/alpha/cat9k_iosxe.17.12.03.SPA.bin
                    is_third_party: False
                  - source_url:  http://sdaso.cisco.com/swim/alpha/cat9k_iosxe.17.17.01prd5.SPA.bin
                    is_third_party: False
                  - source_url:  http://sdaso.cisco.com/swim/alpha/cat9k_iosxe.17.12.04.SPA.bin
                    is_third_party: False

