---
- name: Template
  hosts: dnac
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Create
      cisco.dnac.application_sets_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
      retries: 10
      delay: 1
      register: result
      until: result.status == 200
