---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: User and Role Workflow Manager
      cisco.dnac.user_role_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          user_details:
            - first_name: "ajith"
              last_name: "andrew"
              username: "ajithandrewj"
              email: "ajith.andrew@example.com"
              password: "Ajith@123"
              role_list: ["Super-Admin-Role"]
            - first_name: "syed"
              last_name: "khadeer"
              username: "syedkhadeer"
              email: "syedkhadeer@example.com"
              password: "Syedkhadeer@123"
          role_details:
            - role_name: "Test_Role_1"
              description: "Default role creation"
              assurance:
                - overall: "read"
                  troubleshooting_tools: "write"
              network_analytics:
                - overall: "deny"
              network_design:
                - overall: "deny"
                  image_repository: "read"
              network_provision:
                - overall: "read"
                  eox: "write"
                  image_update: "read"
                  inventory_management:
                    - overall: "write"
                      port_management: "read"
              network_services:
                - overall: "deny"
                  bonjour: "Write"
              platform:
                - overall: "deny"
                  bundles: "read"
              security:
                - overall: "deny"
                  ip_based_access_control: "read"
                  security_advisories: "deny"
              system:
                - overall: "deny"
                  machine_reasoning: "write"
                  system_management: "deny"
              utilities: 
                - overall: "deny"
                  audit_log: "read"

          # role_details:
          #   - role_name: "Test_Role_1"
          #     description: "Default role creation"
          #     assurance:
          #       - overall: "write"
          #         monitoring_and_troubleshooting: "write"
          #         monitoring_settings: "write"
          #         troubleshooting_tools: "deny"
          #     network_analytics:
          #       - data_access: "read"
          #     network_design:
          #       - overall: "write"
          #         advanced_network_settings: "write"
          #         image_repository: "write"
          #         network_hierarchy: "deny"
          #         network_profiles: "read"
          #         network_settings: "deny"
          #         virtual_network: "read"
          #     network_provision:
          #       - overall: "write"
          #         compliance: "write"
          #         eox: "write"
          #         image_update: "deny"
          #         inventory_management:
          #           - overall: "write"
          #             device_configuration: "write"
          #             discovery: "read"
          #             network_device: "write"
          #             port_management: "deny"
          #             topology: "write"
          #         license: "write"
          #         network_telemetry: "write"
          #         pnp: "read"
          #         provision: "deny"
          #     network_services:
          #       - overall: "write"
          #         app_hosting: "write"
          #         bonjour: "write"
          #         stealthwatch: "deny"
          #         umbrella: "write"
          #     platform:
          #       - overall: "write"
          #         apis: "write"
          #         bundles: "deny"
          #         events: "read"
          #         reports: "write"
          #     security:
          #       - overall: "write"
          #         group_based_policy: "read"
          #         ip_based_access_control: "read"
          #         security_advisories: "deny"
          #     system:
          #       - overall: "write"
          #         machine_reasoning: "read"
          #         system_management: "deny"
          #     utilities: 
          #       - overall: "write"
          #         audit_log: "read"
          #         event_viewer: "read"
          #         network_reasoner: "write"
          #         remote_device_support: "write"
          #         scheduler: "write"
          #         search: "write"
