---
name: Unittests

on:
  workflow_dispatch:
  pull_request:

env:
  NAMESPACE: cisco
  COLLECTION_NAME: dnac

jobs:
  Module-unittest:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install -r test-requirements.txt
          ansible-galaxy collection install -f ansible.netcommon -p ./ansible_collections
          # Ensure the current directory is added to PYTHONPATH
          echo "PYTHONPATH=$PWD/ansible_collections:$PYTHONPATH" >> $GITHUB_ENV

      - name: Set env variable for Ansible Collections path
        run: echo "COLLECTIONS_PATHS=$PWD/ansible_collections" >> $GITHUB_ENV

      - name: Run tests
        env:
          COLLECTIONS_PATHS: ${{ env.COLLECTIONS_PATHS }}
        run: |
          base_ref=${{ github.base_ref || github.ref }}
          git diff --name-only "origin/$base_ref" HEAD | grep '^plugins/modules/dnac/.*workflow_manager\.py$' | xargs -I {} bash -c 'unittest_file="tests/unit/modules/dnac/test_$(basename {})"; echo "Running unittest for: $unittest_file"; python -m unittest "$unittest_file"'
          echo "Tests completed successfully."
          python -m unittest tests/unit/modules/dnac/test_user_role_workflow_manager.py
