---
name: Unittests

on:
  workflow_dispatch:
  pull_request:

env:
  NAMESPACE: cisco
  COLLECTION_NAME: dnac

jobs:
  Module-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: Set collection path
        id: set_collection_path
        run: echo "COLLECTION_PATH=${{ github.workspace }}/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0

      - name: Create collections directory
        run: mkdir -p ${{ env.COLLECTION_PATH }}

      - name: Fetch and diff changes
        working-directory: repo
        run: |
          base_ref=${{ github.base_ref || github.ref }}
          git fetch origin $base_ref
          echo "::set-output name=changed_files::$(git diff --name-only "origin/$base_ref" HEAD)"

      - name: Copy repository contents
        run: rsync -av repo/ ${{ env.COLLECTION_PATH }}

      - name: Install dependencies
        working-directory: ${{ env.COLLECTION_PATH }}
        run: |
          pip install -r test-requirements.txt
          ansible-galaxy collection install -f ansible.netcommon -p ${{ env.COLLECTION_PATH }}
          export PYTHONPATH=$PYTHONPATH:${{ env.COLLECTION_PATH }} >> $GITHUB_ENV

      - name: Run tests
        working-directory: ${{ env.COLLECTION_PATH }}
        run: |
          # changed_files="${{ steps.fetch_and_diff.outputs.changed_files }}"
          # echo "$filtered_files"
          # filtered_files=$(echo "$changed_files" | grep '^plugins/modules/dnac/.*workflow_manager\.py$')
          # echo "$filtered_files"
          # echo "$filtered_files" | while IFS= read -r -d '' file; do
          #   unittest_file="tests/unit/modules/dnac/test_$(basename "$file")"
          #   echo "Running unittest for: $unittest_file"
          #   python -m unittest "$unittest_file"
          # done
          # echo "Tests completed successfully."
          python -m unittest tests/unit/modules/dnac/test_user_role_workflow_manager.py
