---
name: Unittests

on:
  workflow_dispatch:
  pull_request:

env:
  NAMESPACE: cisco
  COLLECTION_NAME: dnac

jobs:
  Module-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0

      - name: Create collections directory
        run: mkdir -p ./ansible_collections/${{env.NAMESPACE}}

      - name: Move repository
        run: mv ./repo ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
        run: |
          pip install -r test-requirements.txt
          ansible-galaxy collection install -f ansible.netcommon -p ./ansible_collections
          export PYTHONPATH=$PYTHONPATH:./ansible_collections >> $GITHUB_ENV

      - name: Run tests
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
        run: |
          base_ref=${{ github.base_ref || github.ref }}
          git fetch origin $base_ref
          changed_files=$(git diff --name-only "origin/$base_ref" HEAD)
          echo "$changed_files"

          filtered_files=$(echo "$changed_files" | grep '^plugins/modules/.*workflow_manager\.py$')
          echo "$filtered_files"

          echo "$filtered_files" | while IFS= read -r file; do
            unittest_file="tests/unit/modules/dnac/test_$(basename "$file")"
            echo "Running unittest for: $unittest_file"
            python -m unittest "$unittest_file"
          done

          echo "Tests completed successfully."
