---
name: Unittests

on:
  workflow_dispatch:
  pull_request:

env:
  NAMESPACE: cisco
  COLLECTION_NAME: dnac

jobs:
  Module-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
        run: |
          pip install -r test-requirements.txt
          ansible-galaxy collection install -f ansible.netcommon -p ./ansible_collections
          export PYTHONPATH=$PYTHONPATH:./ansible_collections

      - name: Run tests
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
        run: |
          base_ref=${{ github.base_ref || github.ref }}
          git diff --name-only "origin/$base_ref" HEAD | while IFS= read -r -d '' file; do
            echo "File: $file"
            if [[ "$file" == plugins/modules/dnac/*workflow_manager.py ]]; then
              file_name=$(basename "$file")
              if [[ "$file_name" != test_* ]]; then
                unittest_file="tests/unit/modules/dnac/test_$file_name"
                echo "Running unittest for file: $unittest_file"
                python -m unittest "$unittest_file"
              fi
            fi
          done
          python -m unittest tests/unit/modules/dnac/test_user_role_workflow_manager.py
          echo "Tests completed successfully."
